#!/usr/bin/env bash

set -euo pipefail
set -x

# Make sure we always run from the root
SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPTS_DIR/.."

#########
# USAGE #
#########

function title() {
    echo "Builds ckSOL minter canister"
}

function usage() {
    cat << EOF

Usage:
  $0 [--only-dependencies]

Options:
  --only-dependencies          only build rust dependencies (no js build, no wasm optimization)
EOF
}

function help() {
    cat << EOF

Builds the ckSOL minter canister.

NOTE: This requires a working rust toolchain as well as ic-wasm.
EOF

}

ONLY_DEPS=
RUN_CARGO_TEST=
CANISTERS=()

while [[ $# -gt 0  ]]
do
    case "$1" in
        -h|--help)
            title
            usage
            help
            exit 0
            ;;
        --only-dependencies)
            ONLY_DEPS=1
            shift
            ;;
        --test)
            RUN_CARGO_TEST=1
            shift
            ;;
        --cksol_minter)
            CANISTERS+=("cksol_minter")
            shift
            ;;
        *)
            echo "ERROR: unknown argument $1"
            usage
            echo
            echo "Use 'build --help' for more information"
            exit 1
            ;;
    esac
done

# Checking for dependencies
REPRODUCIBLE_IC_WASM_VERSION="ic-wasm 0.3.5"
if ! command -v ic-wasm > /dev/null
then
    echo "could not find ic-wasm, please run the following command:"
    echo "  cargo install --locked ic-wasm --version 0.3.5"
    exit 1
fi
if [[ "$(ic-wasm --version)" != "$REPRODUCIBLE_IC_WASM_VERSION" ]]
then
    echo "WARNING: found $(ic-wasm --version) but the reproducible build uses $REPRODUCIBLE_IC_WASM_VERSION."
    echo "The resulting Wasm may differ from the one produced by ./scripts/docker-build."
fi

function build_canister() {
    local canister=$1
    shift
    local extra_build_args=("$@")

    echo "Building $canister"
    echo

    SRC_DIR="/src"
    TARGET="wasm32-unknown-unknown"
    # standardize source references
    CARGO_HOME="${CARGO_HOME:-"$HOME/.cargo"}"
    RUSTFLAGS="--remap-path-prefix $CARGO_HOME=/cargo"

    cargo_build_args=(
        --locked
        --target "$TARGET"
        --release
        --package "$canister"
        --jobs 1
        )
    # XXX: for bash > 4.4, empty arrays are considered unset, so do some substitution
    cargo_build_args+=(${extra_build_args[@]+"${extra_build_args[@]}"})

    echo Running cargo build "${cargo_build_args[@]}"
    echo RUSTFLAGS: "$RUSTFLAGS"

    RUSTFLAGS="$RUSTFLAGS" cargo build "${cargo_build_args[@]}"

    if [ "$RUN_CARGO_TEST" == "1" ]
    then
        cargo test
    fi

    if [ "$ONLY_DEPS" != "1" ]
    then
        local wasm_out="wasms/$canister.wasm"
        mkdir -p wasms
        ic-wasm \
            "./target/$TARGET/release/$canister.wasm" \
            -o "$wasm_out" \
            shrink
        ic-wasm "$wasm_out" -o "$wasm_out" metadata candid:service -f "minter/$canister.did" -v public
        ic-wasm "$wasm_out" -o "$wasm_out" metadata candid:args -d "(MinterArg)" -v public

        # Write metadata for dfx
        wasm_url="https://github.com/dfinity/cksol/releases/latest/download/$canister.wasm.gz"
        # TODO: add init_guide once documentation is available
        metadata_json="{\"pullable\":{\"wasm_url\":\"$wasm_url\",\"dependencies\":[]}}"
        ic-wasm "$wasm_out" -o "$wasm_out" metadata dfx -d "$metadata_json" -v public

        gzip --no-name --force "$wasm_out"
    fi
}

for canister in "${CANISTERS[@]}"
do
    build_canister "$canister"
done
