name: 'ckSOL'

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "README.md"
env:
  SOLANA_CLI_VERSION: "2.1.15"
  POCKET_IC_SERVER_VERSION: "12.0.0"
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Check code'
        run: |
          cargo fmt --all -- --check
          cargo clippy --locked --verbose --tests --benches --workspace -- -D clippy::all
          cargo clippy --locked --verbose --target wasm32-unknown-unknown -p cksol-minter -- -D clippy::all

      - name: 'Install cargo-sort'
        run: cargo install cargo-sort

      - name: 'Check Cargo.toml'
        run: cargo sort --workspace --check

  reproducible-build:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Docker build'
        run: ./scripts/docker-build

      - name: 'Archive Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: cksol-minter.wasm.gz
          path: ./wasms/cksol-minter.wasm.gz
          if-no-files-found: error
          compression-level: 0

      - name: 'Add summary'
        run: |
          hash=`sha256sum ./wasms/cksol-minter.wasm.gz`
          echo "SHA-256 :hash: ${hash}" >> $GITHUB_STEP_SUMMARY

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Run unit tests'
        run: cargo test --locked --workspace --exclude cksol-int-tests

  integration-tests:
    needs: [ reproducible-build ]
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Download Artifacts'
        uses: actions/download-artifact@v4
        with:
          name: cksol-minter.wasm.gz

      - name: 'Set CKSOL_MINTER_WASM_PATH for load_wasm'
        run: |
          echo "CKSOL_MINTER_WASM_PATH=$GITHUB_WORKSPACE/cksol-minter.wasm.gz" >> "$GITHUB_ENV"

      - name: 'Install PocketIC server'
        uses: dfinity/pocketic@main
        with:
          pocket-ic-server-version: ${{ env.POCKET_IC_SERVER_VERSION }}

      - name: 'Install Solana CLI'
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v${SOLANA_CLI_VERSION}/install)"
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash

      - name: 'Start Solana test validator'
        run: |
          solana-test-validator &

      - name: 'Cargo test'
        run: cargo test --package cksol-int-tests -- --test-threads 2 --nocapture
